version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Persist BadgerDB data
      - ./data:/root/data
    environment:
      # Add your environment variables here
      - PORT=8080
      # - JWT_SECRET=your_secret_here
      # - AUDIUS_API_URL=https://api.audius.co
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s